Information: URL recovery. lxw_KeyError: http://www.cnvd.org.cn/	2015-09-08-14:46:04

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-09-08-14:46:04
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 675, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.cnvd.org.cn_'

EMAIL SENDING: 	2015-09-08-14:46:15

EMAIL SENDING SUCCESS: 	2015-09-08-14:46:16

Monitor Finished.   Monitor Time: 2015-09-08-14:46:16.   Time Cost: 0'12"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
