TEST EMAIL SENDING: 	2015-06-11-23:00:23

TEST EMAIL SENDING: 	2015-06-11-23:02:02

TEST EMAIL SENDING ERROR: Other Exception	2015-06-11-23:04:13
Traceback (most recent call last):
  File "config.py", line 231, in testSendEmail
    sm = smtplib.SMTP(smtpServer)
  File "/usr/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 110] Connection timed out

------------------------------------------------------------------------------

TEST EMAIL SENDING: 	2015-06-11-23:05:41

TEST EMAIL SENDING ERROR: Other Exception	2015-06-11-23:07:52
Traceback (most recent call last):
  File "config.py", line 231, in testSendEmail
    sm = smtplib.SMTP(smtpServer)
  File "/usr/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 110] Connection timed out

------------------------------------------------------------------------------

TEST EMAIL SENDING: 	2015-06-11-23:08:02

TEST EMAIL SENDING: 	2015-06-11-23:08:38

TEST EMAIL SENDING: 	2015-06-11-23:09:57

TEST EMAIL SENDING: 	2015-06-11-23:12:51

TEST EMAIL SENDING: 	2015-06-11-23:15:22

EMAIL SENDING: 	2015-06-11-23:18:07

EMAIL SENDING ERROR: 	2015-06-11-23:20:14
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 261, in sendEmail
    sm = smtplib.SMTP(smtpServer)
  File "/usr/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 110] Connection timed out

lxw_Exception.: .db.conf pickle Error	2015-06-11-23:20:14
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 162, in getDBUser
    host = decode(host)
  File "/home/cnnic/monitorURL/myUtils.py", line 91, in decode
    result = base64.b64decode(string)
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

------------------------------------------------------------------------------

lxw_Exception.: 	2015-06-11-23:20:15
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 194, in updateCriterion
    conn = MySQLdb.connect(host=Host, user=username, passwd=password, port=Port)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required

------------------------------------------------------------------------------

Monitor Finished.   Monitor Time: 2015-06-11-23:20:15.   Time Cost: 2'43"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
